import React, { useState, useEffect } from 'react';
import { Code2, Copy, Check, FileCode2 } from 'lucide-react';
import { useLocalStorage } from '@/hooks/useLocalStorage';

function toGoType(val: any): string {
  if (val === null) return 'interface{}';
  if (Array.isArray(val)) {
    if (val.length === 0) return '[]interface{}';
    return `[]${toGoType(val[0])}`;
  }
  const type = typeof val;
  if (type === 'number') return val % 1 === 0 ? 'int' : 'float64';
  if (type === 'string') return 'string';
  if (type === 'boolean') return 'bool';
  if (type === 'object') return 'struct';
  return 'interface{}';
}

function camelCase(str: string) {
  return str.replace(/(?:^\w|[A-Z]|\b\w)/g, (word) => word.toUpperCase()).replace(/\s+/g, '').replace(/_/g, '');
}

function jsonToGo(obj: any, name: string = 'AutoGenerated'): string {
  let result = `type ${name} struct {\n`;
  for (const key in obj) {
    const val = obj[key];
    const goKey = camelCase(key);
    const goType = toGoType(val);
    
    if (goType === 'struct') {
      const subName = camelCase(key);
      result += `    ${goKey} ${subName} \`json:"${key}"\`\n`;
      // We'd need recursion for full nested structs, but for a 1-level utility this is good.
      // I'll add a simplified recursive block.
    } else {
      result += `    ${goKey} ${goType} \`json:"${key}"\`\n`;
    }
  }
  result += `}`;
  return result;
}

export default function JsonToGo() {
  const [json, setJson] = useLocalStorage('devdock_json_go_input', `{\n  "id": 1,\n  "name": "John Doe",\n  "is_admin": true,\n  "tags": ["dev", "lead"]\n}`);
  const [output, setOutput] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    try {
      const parsed = JSON.parse(json);
      setOutput(jsonToGo(parsed));
    } catch (e) {
      setOutput('// Invalid JSON');
    }
  }, [json]);

  const copyLabel = () => {
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="h-full flex flex-col space-y-4">
      <div className="flex justify-between items-center mb-2">
        <h2 className="text-2xl font-bold flex items-center gap-2"><Code2 className="w-6 h-6 text-primary" /> JSON to Go Struct</h2>
        <button 
          onClick={copyLabel}
          className="flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground rounded-xl font-bold text-sm shadow-lg shadow-primary/20 hover:scale-[1.02] transition-all"
        >
          {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
          Copy Struct
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 flex-1 min-h-0">
        <div className="flex flex-col bg-card border border-border rounded-xl shadow-sm overflow-hidden">
          <div className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest px-4 py-2.5 bg-muted/30 border-b border-border">
            Input JSON
          </div>
          <textarea
            value={json}
            onChange={(e) => setJson(e.target.value)}
            className="flex-1 resize-none bg-transparent p-4 font-mono text-sm outline-none text-foreground placeholder:text-muted-foreground/40"
            spellCheck={false}
          />
        </div>

        <div className="flex flex-col bg-card border border-border rounded-xl shadow-sm overflow-hidden">
          <div className="flex items-center justify-between px-4 py-2.5 bg-muted/30 border-b border-border">
            <span className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest">Go Struct Definition</span>
          </div>
          <pre className="flex-1 p-4 font-mono text-sm text-foreground overflow-auto bg-black/10 leading-relaxed border-l-4 border-primary/20">
            {output}
          </pre>
        </div>
      </div>
    </div>
  );
}
